/**
 * Phase 3.5 — the three consumer emitters. Each takes the same TokenSet, so the
 * DTCG document and these are four views of one build, not four pipelines.
 *
 * **CSS** keeps OKLCH, because the whole library's output is expressible as
 * `oklch(l c h)` and that was a settled decision. A P3 set emits the sRGB hex
 * first and the wide value inside `@media (color-gamut: p3)`, so the fallback is
 * the sibling the solver pinned rather than whatever the browser clips to.
 *
 * **Tailwind v4** is `@theme`, whose custom properties become utilities. Modes
 * are a `.dark` (or `[data-theme=dark]`) override of the same properties, which
 * is what the framework's dark variant reads.
 *
 * **Figma Variables** is sRGB-only, so OKLCH stays canonical in the DTCG file
 * and Figma gets the quantized hex. Variables are keyed by the stable ID, not by
 * name, and each carries a value per mode — the same one-token-two-values shape
 * the build uses, which is where that shape came from.
 */
import type { TokenSet, Mode, SemanticToken } from './build.ts';

const cssName = (parts: string[]) => parts.join('-').replace(/[^a-zA-Z0-9-]/g, '-').replace(/-+/g, '-');

export interface CssOptions {
  /** Prefix for the custom properties. Default `color`. */
  prefix?: string;
  /** How the dark mode is selected. Default `.dark, [data-theme="dark"]`. */
  darkSelector?: string;
  /** Emit `@media (prefers-color-scheme: dark)` as well. Default true. */
  prefersColorScheme?: boolean;
  /** Include the primitives, not just the semantic layer. Default true. */
  primitives?: boolean;
  /** Annotate each semantic property with its measured contrast. Default true. */
  comments?: boolean;
}

export function toCSS(set: TokenSet, opts: CssOptions = {}): string {
  const prefix = opts.prefix ?? 'color';
  const darkSel = opts.darkSelector ?? '.dark, [data-theme="dark"]';
  const withPrimitives = opts.primitives ?? true;
  const comments = opts.comments ?? true;
  const wide = set.gamut === 'p3';

  const lines: string[] = [];
  lines.push(`/* ${set.name}`);
  lines.push(` * Generated by palette-dna from ${set.provenance.referenceName}${set.provenance.darkReference ? `; dark mode ${set.provenance.darkReference.kind}` : ''}.`);
  if (set.provenance.seed) lines.push(` * Seed pinned at step ${set.provenance.seedStep}.`);
  lines.push(` * OKLCH is canonical.${wide ? ' The sRGB values come first; the P3 values override them where the display can show them.' : ''}`);
  lines.push(' */');

  const block = (mode: Mode, srgb: boolean): string[] => {
    const out: string[] = [];
    if (withPrimitives) {
      for (const p of set.primitives) {
        const v = p.values[mode];
        if (!v) continue;
        out.push(`  --${cssName([prefix, p.family, p.step])}: ${srgb ? v.hex : v.css};`);
      }
      out.push('');
    }
    for (const s of set.semantics) {
      const v = s.values[mode];
      if (!v) continue;
      const a = s.alias[mode];
      const val = a && withPrimitives ? `var(--${cssName([prefix, a.family, a.step])})` : srgb ? v.hex : v.css;
      const ev = s.evidence[mode];
      const note = comments && ev
        ? `  /* ${ev.stepKey ? `${a?.family ?? ''}-${ev.stepKey}` : (s.literal[mode] ?? 'literal')} · ${ev.against.wcag.toFixed(2)}:1, Lc ${ev.against.apca.toFixed(0)} on ${ev.against.role}${ev.met ? '' : ' — REQUIREMENT NOT MET'} */`
        : '';
      out.push(`  --${cssName([prefix, ...s.path])}: ${val};${note}`);
    }
    return out;
  };

  /** One selector's worth of declarations. */
  const rule = (selector: string, mode: Mode, srgb: boolean, indent = ''): string[] => [
    '', `${indent}${selector} {`, ...block(mode, srgb).map((l) => (l ? indent + l : l)), `${indent}}`,
  ];

  const prefers = opts.prefersColorScheme ?? true;
  const autoDark = ':root:not(.light):not([data-theme="light"])';

  // An sRGB set emits OKLCH straight: the values *are* the quantized sRGB colours, so a
  // hex fallback would say the same thing twice. A P3 set emits the sRGB sibling the
  // solver pinned as the base, and the wide values only where the display can show them —
  // so a narrow display gets the sibling rather than whatever the browser clips to.
  lines.push(...rule(':root', 'light', wide));
  lines.push(...rule(darkSel, 'dark', wide));
  if (prefers) {
    lines.push('', '@media (prefers-color-scheme: dark) {', ...rule(autoDark, 'dark', wide, '  '), '}');
  }
  if (wide) {
    lines.push('', '@supports (color: color(display-p3 0 0 0)) {', '  @media (color-gamut: p3) {');
    lines.push(...rule(':root', 'light', false, '    '));
    lines.push(...rule(darkSel, 'dark', false, '    '));
    if (prefers) lines.push('', '    @media (prefers-color-scheme: dark) {', ...rule(autoDark, 'dark', false, '      '), '    }');
    lines.push('  }', '}');
  }
  return lines.join('\n') + '\n';
}

export interface TailwindOptions {
  /** Namespace inside `@theme`. Default `color`, which makes `bg-brand-600` and friends. */
  namespace?: string;
  darkSelector?: string;
  primitives?: boolean;
}

export function toTailwind(set: TokenSet, opts: TailwindOptions = {}): string {
  const ns = opts.namespace ?? 'color';
  const darkSel = opts.darkSelector ?? '.dark, [data-theme="dark"]';
  const withPrimitives = opts.primitives ?? true;
  const lines: string[] = [];
  lines.push(`/* ${set.name} — Tailwind v4 theme, generated by palette-dna.`);
  lines.push(` * \`@theme\` turns each custom property into a utility: --${ns}-brand-600 gives bg-brand-600, text-brand-600 and the rest.`);
  lines.push(' * The dark values override the same properties, which is what the dark variant reads.');
  lines.push(' */');
  lines.push('', '@theme {');
  if (withPrimitives) {
    for (const p of set.primitives) {
      const v = p.values['light'];
      if (v) lines.push(`  --${ns}-${cssName([p.family, p.step])}: ${v.css};`);
    }
    lines.push('');
  }
  for (const s of set.semantics) {
    const v = s.values['light'];
    if (v) lines.push(`  --${ns}-${cssName(s.path)}: ${v.css};`);
  }
  lines.push('}');
  lines.push('', `${darkSel} {`);
  if (withPrimitives) for (const p of set.primitives) { const v = p.values['dark']; if (v) lines.push(`  --${ns}-${cssName([p.family, p.step])}: ${v.css};`); }
  for (const s of set.semantics) { const v = s.values['dark']; if (v) lines.push(`  --${ns}-${cssName(s.path)}: ${v.css};`); }
  lines.push('}');
  return lines.join('\n') + '\n';
}

export interface FigmaVariable {
  /** The stable token ID — what a plugin should key on, so a rename is a rename and not a new variable. */
  id: string;
  name: string;
  resolvedType: 'COLOR';
  scopes: string[];
  description: string;
  /** sRGB, 0–1 per channel, one entry per mode. Figma has no wide-gamut colour. */
  valuesByMode: Record<string, { r: number; g: number; b: number; a: number }>;
  /** What the value would have been in the output gamut, and how far the sRGB value sits from it. */
  wideGamut?: Record<string, { value: string; deltaEOK: number }>;
  codeSyntax?: { WEB: string };
}

export interface FigmaCollection {
  name: string;
  modes: string[];
  variables: FigmaVariable[];
}

export interface FigmaFile {
  $schema: 'palette-dna/figma-variables/1';
  note: string;
  collections: FigmaCollection[];
}

const hexToRgb = (hex: string) => ({
  r: parseInt(hex.slice(1, 3), 16) / 255,
  g: parseInt(hex.slice(3, 5), 16) / 255,
  b: parseInt(hex.slice(5, 7), 16) / 255,
  a: 1,
});

/** Figma variable scopes, so a fill token does not offer itself as a stroke. */
function scopesFor(s: SemanticToken): string[] {
  switch (s.path[0]) {
    case 'content': return ['TEXT_FILL'];
    case 'icon': return ['SHAPE_FILL', 'FRAME_FILL'];
    case 'border': return ['STROKE_COLOR'];
    case 'background':
    case 'surface': return ['FRAME_FILL', 'SHAPE_FILL'];
    default: return ['ALL_SCOPES'];
  }
}

export function toFigma(set: TokenSet): FigmaFile {
  const modes = set.modes.map((m) => m.charAt(0).toUpperCase() + m.slice(1));
  const modeKey = (m: Mode) => m.charAt(0).toUpperCase() + m.slice(1);

  const primitives: FigmaVariable[] = set.primitives.map((p) => ({
    id: p.id,
    name: `${p.family}/${p.step}`,
    resolvedType: 'COLOR',
    scopes: ['ALL_SCOPES'],
    description: `${p.kind} primitive, step ${p.step}${p.evidence['light']?.isSeed || p.evidence['dark']?.isSeed ? ' — the seed' : ''}`,
    valuesByMode: Object.fromEntries(set.modes.filter((m) => p.values[m]).map((m) => [modeKey(m), hexToRgb(p.values[m]!.hex)])),
    ...(set.gamut === 'p3'
      ? { wideGamut: Object.fromEntries(set.modes.filter((m) => p.values[m]).map((m) => [modeKey(m), { value: p.values[m]!.native, deltaEOK: Number(p.values[m]!.siblingDeltaE.toFixed(5)) }])) }
      : {}),
    codeSyntax: { WEB: `var(--color-${cssName([p.family, p.step])})` },
  }));

  const semantics: FigmaVariable[] = set.semantics.map((s) => ({
    id: s.id,
    name: s.path.join('/'),
    resolvedType: 'COLOR',
    scopes: scopesFor(s),
    description: `${s.spec.description} Requirement: ${s.spec.source}.`,
    valuesByMode: Object.fromEntries(set.modes.filter((m) => s.values[m]).map((m) => [modeKey(m), hexToRgb(s.values[m]!.hex)])),
    ...(set.gamut === 'p3'
      ? { wideGamut: Object.fromEntries(set.modes.filter((m) => s.values[m]).map((m) => [modeKey(m), { value: s.values[m]!.native, deltaEOK: Number(s.values[m]!.siblingDeltaE.toFixed(5)) }])) }
      : {}),
    codeSyntax: { WEB: `var(--color-${cssName(s.path)})` },
  }));

  const clipped = [...set.primitives, ...set.semantics].filter((t) => set.modes.some((m) => (t.values[m]?.siblingDeltaE ?? 0) > 0.02)).length;

  return {
    $schema: 'palette-dna/figma-variables/1',
    note:
      `Figma has no wide-gamut colour, so these are the sRGB siblings; OKLCH stays canonical in the DTCG file. ` +
      (set.gamut === 'p3'
        ? `${clipped} of ${set.primitives.length + set.semantics.length} tokens sit more than one JND outside sRGB and differ visibly from the P3 value — each carries its own ΔEOK under \`wideGamut\`. `
        : '') +
      `Variables are keyed by \`id\`: match on that, not on \`name\`, so a rename stays a rename.`,
    collections: [
      { name: `${set.name} — primitives`, modes, variables: primitives },
      { name: `${set.name} — semantic`, modes, variables: semantics },
    ],
  };
}

/** A short human report of what the assignment decided and what it could not. */
export function toReport(set: TokenSet): string {
  const lines: string[] = [];
  lines.push(`${set.name}`);
  lines.push(`  reference ${set.provenance.referenceName} (${set.provenance.reference}), dark ${set.provenance.darkReference?.kind ?? 'n/a'}, ${set.gamut}, spacing ${set.provenance.spacing}`);
  if (set.provenance.seed) lines.push(`  seed pinned at step ${set.provenance.seedStep}`);
  lines.push('');
  lines.push(`  role                        light                        dark                         measured against`);
  for (const s of set.semantics) {
    const cell = (m: Mode) => {
      const e = s.evidence[m];
      if (!e) return ''.padEnd(29);
      const where = e.stepKey ?? e.chosenFrom ?? s.literal[m] ?? '—';
      return `${where} ${e.against.wcag.toFixed(2)}:1 Lc${e.against.apca.toFixed(0)}${e.met ? '' : ' ✗'}`.padEnd(29);
    };
    lines.push(`  ${s.role.padEnd(26)}${cell('light')}${cell('dark')}${s.evidence['light']?.against.role ?? ''}`);
  }
  const unmet = set.semantics.flatMap((s) => set.modes.filter((m) => s.evidence[m] && !s.evidence[m]!.met).map((m) => `${m} ${s.role}: ${s.evidence[m]!.shortfall}`));
  if (unmet.length) {
    lines.push('', '  unmet requirements:');
    for (const u of unmet) lines.push(`    ${u}`);
  }
  return lines.join('\n');
}
